service: public-badges-registry-flow
variablesResolutionMode: 20210326
plugins:
  - serverless-plugin-monorepo

custom:
  parameter_prefix: public-badges/${opt:stage}
  event_bus: ${ssm:/${self:custom.parameter_prefix}/registry/event_bus}
  role: ${ssm:/${self:custom.parameter_prefix}/api/role}
  registry_bucket: ${ssm:/${self:custom.parameter_prefix}/registry/bucket}
  registry_lookup: ${ssm:/${self:custom.parameter_prefix}/registry/lookup_table}
  function_prefix: public-badges-${opt:stage}
  api: ${self:custom.function_prefix}-graphql
  approve_organization: ${self:custom.function_prefix}.approve-organization
  save_organization: ${self:custom.function_prefix}.save-organization
  update_registry_lookup: ${self:custom.function_prefix}-update-registry-lookup

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  eventBridge:
    useCloudFormation: true
  lambdaHashingVersion: 20201221
  iam:
    role: ${self:custom.role}

functions:
  saveOrganization:
    handler: dist/index.saveOrganization
    events:
      - eventBridge:
          eventBus: ${self:custom.event_bus}
          pattern:
            source:
              - ${self:custom.api}
              - ${self:custom.approve_organization}
            detail-type: 
             - ORGANIZATION_REGISTRATION_REQUESTED
             - ORGANIZATION_APPROVAL_ACCEPTED
    environment:
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
      HANDLER_NAME: ${self:custom.save_organization}
  approveOrganization:
    handler: dist/index.approveOrganization
    events:
      - eventBridge:
          eventBus: ${self:custom.event_bus}
          pattern:
            source:
              - ${self:custom.save_organization}
            detail-type:
              - ORGANIZATION_APPROVAL_REQUESTED
    environment:
      HANDLER_NAME: ${self:custom.approve_organization}
  updateRegistry:
    handler: dist/index.updateRegistry
    events:
      - eventBridge:
          eventBus: ${self:custom.event_bus}
          pattern:
            source:
              - ${self:custom.api}
              - ${self:custom.approve_organization}
            detail-type: 
             - ORGANIZATION_REGISTRATION_REQUESTED
             - ORGANIZATION_APPROVAL_ACCEPTED
    environment:
      REGISTRY_LOOKUP_TABLE: ${self:custom.registry_lookup}
      HANDLER_NAME: ${self:custom.update_registry_lookup}
