/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ApprovedPublicBadge,
} from './types';
import {
  ModalPositioning,
} from './interfaces';

export namespace Components {
  interface PublicbadgesCircle {
    'badgesCount': number;
    'interactive': boolean;
    'testMode': boolean;
  }
  interface PublicbadgesDrawer {
    'badgeColor': string;
    'language': "EN" | "NL";
    'modalTheme': "dark" | "light";
    'testDomain': string;
    'testMode': boolean;
  }
  interface PublicbadgesModal {
    'badges': ApprovedPublicBadge[];
    'language': "EN" | "NL";
    'positioning': ModalPositioning;
    'theme': string;
  }
}

declare global {


  interface HTMLPublicbadgesCircleElement extends Components.PublicbadgesCircle, HTMLStencilElement {}
  var HTMLPublicbadgesCircleElement: {
    prototype: HTMLPublicbadgesCircleElement;
    new (): HTMLPublicbadgesCircleElement;
  };

  interface HTMLPublicbadgesDrawerElement extends Components.PublicbadgesDrawer, HTMLStencilElement {}
  var HTMLPublicbadgesDrawerElement: {
    prototype: HTMLPublicbadgesDrawerElement;
    new (): HTMLPublicbadgesDrawerElement;
  };

  interface HTMLPublicbadgesModalElement extends Components.PublicbadgesModal, HTMLStencilElement {}
  var HTMLPublicbadgesModalElement: {
    prototype: HTMLPublicbadgesModalElement;
    new (): HTMLPublicbadgesModalElement;
  };
  interface HTMLElementTagNameMap {
    'publicbadges-circle': HTMLPublicbadgesCircleElement;
    'publicbadges-drawer': HTMLPublicbadgesDrawerElement;
    'publicbadges-modal': HTMLPublicbadgesModalElement;
  }
}

declare namespace LocalJSX {
  interface PublicbadgesCircle {
    'badgesCount'?: number;
    'interactive'?: boolean;
    'testMode'?: boolean;
  }
  interface PublicbadgesDrawer {
    'badgeColor'?: string;
    'language'?: "EN" | "NL";
    'modalTheme'?: "dark" | "light";
    'testDomain'?: string;
    'testMode'?: boolean;
  }
  interface PublicbadgesModal {
    'badges'?: ApprovedPublicBadge[];
    'language'?: "EN" | "NL";
    'onCloseDrawer'?: (event: CustomEvent<any>) => void;
    'positioning'?: ModalPositioning;
    'theme'?: string;
  }

  interface IntrinsicElements {
    'publicbadges-circle': PublicbadgesCircle;
    'publicbadges-drawer': PublicbadgesDrawer;
    'publicbadges-modal': PublicbadgesModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'publicbadges-circle': LocalJSX.PublicbadgesCircle & JSXBase.HTMLAttributes<HTMLPublicbadgesCircleElement>;
      'publicbadges-drawer': LocalJSX.PublicbadgesDrawer & JSXBase.HTMLAttributes<HTMLPublicbadgesDrawerElement>;
      'publicbadges-modal': LocalJSX.PublicbadgesModal & JSXBase.HTMLAttributes<HTMLPublicbadgesModalElement>;
    }
  }
}


