service: public-badges-api
variablesResolutionMode: 20210326

custom:
  registry_bucket: ${ssm:/${opt:stage}/registry/bucket}
  registry_lookup: ${ssm:/${opt:stage}/registry/lookup_table}
  organization-status-index: ${ssm:/${opt:stage}/registry/indices/organization_status}
  graphql: public-badges.graphql-${opt:stage}

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.registry_lookup}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.registry_lookup}/index/*"

functions:
  graphql:
    handler: dist/index.graphql
    package:
      individually: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: any
          cors: true
    environment:
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
      HANDLER_NAME: ${self:custom.graphql}
      REGISTRY_LOOKUP_TABLE: ${self:custom.registry_lookup_table}
      ORGANIZATION_STATUS_INDEX: ${self:custom.organization-status-index}
