service: public-badges-api
variablesResolutionMode: 20210326
  

custom:
  parameter_prefix: public-badges/${opt:stage}
  registry_bucket: ${ssm:/${self:custom.parameter_prefix}/registry/bucket}
  registry_lookup: ${ssm:/${self:custom.parameter_prefix}/registry/lookup_table}
  organization-status-index: ${ssm:/${self:custom.parameter_prefix}/registry/indices/organization_status}
  role: ${ssm:/${self:custom.parameter_prefix}/api/role}
  graphql: public-badges-${opt:stage}-graphql

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  iam:
    role: ${self:custom.role}

functions:
  graphql: 
    handler: dist/handler.graphql
    package:
      individually: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: any
          cors: true
    environment:
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
      HANDLER_NAME: ${self:custom.graphql}
      REGISTRY_LOOKUP_TABLE: ${self:custom.registry_lookup}
      ORGANIZATION_STATUS_INDEX: ${self:custom.organization-status-index}
