name: 'deploy all'

on:
  push:
    branches:
    - master
    - infra
  pull_request:

jobs:
  infra:
    name: 'Infra'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ secrets.WORKSPACE }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
  deployAPI:
    name: 'Deploy API'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: yarn install
    - name: Use Husky
      run: yarn prepare
    - name: Build Packages Xode
      run: yarn build:packages
    - name: Build API code
      run: yarn build:api
