name: "deploy all"

on:
  push:
    branches:
      - master
      - infra
  pull_request:

jobs:
  infra:
    name: "Deploy Infra"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          TF_WORKSPACE: |
            stable:production
            master:dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Install Dependencies
        run: npm install -g add remark-cli remark-html
      - name: Make Output Dir form Email Templates
        run: mkdir emailTemplates/compiled
      - name: Render Email Templates to TXT
        run: remark emailTemplates/*.md -o emailTemplates/compiled/
      - name: Render Email Templates to HTML
        run: remark emailTemplates/*.md --use html -o emailTemplates/compiled/
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
  services:
    name: "Deploy Services"
    needs: infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          SLS_ENVIRONMENT: |
            stable: 'production'
            master: 'dev'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: yarn install
      - name: Use Husky
        run: yarn prepare
      - name: Build Packages Code
        run: yarn build:packages
      - name: Build Services code
        run: yarn build:services
      - name: Deploy Services Code
        run: yarn deploy:services
